### ISSUE TITLE
Lotus Nodes doesn't work in ComfyUI 0.3.65

### ISSUE THREAD

**Issue by cdordelly** [kijai/ComfyUI-Lotus#11]
Hi!

I'm trying to install ComfyUI-Lotus but looks like it can't work in ComfyUI 0.3.65, I receive this error after installation and I can't see the nodes:

Error message occurred while importing the 'ComfyUI-Lotus' module.

Traceback (most recent call last):
  File "Y:\AI\ComfyUI\ComfyUI\nodes.py", line 2131, in load_custom_node
    module_spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Y:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Lotus\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "Y:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Lotus\nodes.py", line 9, in <module>
    from diffusers.models import UNet2DConditionModel
  File "Y:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
    ...<12 lines>...
    )
  File "Y:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "Y:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (Y:\AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

**Comment by NgoChingYee** [comment]
I just need to upgrade both diffusers and huggingface_hub. This works for me.
diffusers==0.36.0
huggingface-hub==0.36.0
